project:
  name: Organization API
  debug: true
  environment: development

database:
  host: localhost  # for local launch
  # host: postgres

  port: 5432
  user: postgres
  password: postgres
  name: organization
  sslmode: disable
  migrations: migrations
  driver: pgx

rest:
  host: localhost
  port: 8080